version: '3'
services:
  db: 
    image: mysql
    container_name: db
    command: mysqld --character-set-server=utf8 --container-server=utf8_general_ci
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jesse
      MYSQL_PASSWORD: 123
    volumes:
      - /d/docker/beta/mysql-init:/docker-entrypoint-initdb.d
  web:
    build: .
    container_name: 'aspnetcore'
    ports:
      - '8002:80'
    depends_on:
      - db  